<a href="https://colab.research.google.com/github/okuraseki/CursoEDA/blob/main/creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list(range(0,10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(0,10) # similar a range de python, pero genra un array de np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20,2) # este es el steper,

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.zeros(3) # genera un array relleno de 0

array([0., 0., 0.])

In [8]:
# una matriz tambien
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# tambien existe para crear relleno de 1
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,10,10) # valor que inicia, valor que termine, cuantos numeros

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [11]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [12]:
# algebra lineal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# valor aleatorio
np.random.rand()

0.4748056265529603

In [14]:
# array aleatorio
np.random.rand(4) # pasando el numero de elementos

array([0.32607068, 0.56433081, 0.02018411, 0.47200351])

In [17]:
# matriz de numero aleatorios
np.random.rand(4,4)

array([[0.79803651, 0.99954983, 0.58894745, 0.15147151],
       [0.08175957, 0.41081219, 0.69992945, 0.88991636],
       [0.34390913, 0.87924317, 0.50718499, 0.56762523],
       [0.59809615, 0.76665226, 0.11282707, 0.81809639]])

In [18]:
np.random.randint(1,15)
# entero aleatorio


9

In [19]:
# estructuro de entero aleatorios
np.random.randint(1,100,(10,10)) # valor aleat inicial, valor aleat final, estructura (10,10)

array([[37, 34, 94, 96, 61, 95, 64, 93, 80, 82],
       [75, 78, 61, 54,  8, 82, 58,  9, 52, 19],
       [44, 28, 39, 31, 67, 33, 96, 29, 10, 40],
       [68, 69, 92, 80, 48,  4, 72, 12, 28, 49],
       [ 8, 97, 29, 58, 50, 77, 16,  7, 99, 60],
       [32,  4, 13, 22, 77, 18, 44, 77, 21,  9],
       [75, 34, 89, 46, 85, 32, 77, 46, 61, 44],
       [ 1, 73, 85, 56, 93, 26, 58, 22,  7, 69],
       [55, 13, 70, 11, 37, 56, 99, 72, 45, 92],
       [55, 11, 89, 78, 52,  2, 86, 42, 14, 76]])