<a href="https://colab.research.google.com/github/okuraseki/CursoEDA/blob/main/Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pn




¿Por qué NumPy?

Es una librería enfocada al cálculo númerico y manejo de Arrays.

    Es muy veloz, hasta 50 veces más rápido que usar una lista de Python o C.
    Optimiza el almacenamiento en memoria.
    Además, maneja distintos tipos de datos.

Es una librería muy poderosa, se pueden crear redes neuronales desde cero.
¿Por qué Pandas?

Pandas está enfocada a la manipulación y análisis de datos.

    Al estar construido sobre NumPy veloz.
    Requiere poco código para manipular los datos.
    Soporta múltiples formatos de archivos.
    Ordena los datos en una alienación inteligente.

Se pueden manejar grandes cantidades de datos, hacer analítica y crear dahsboards.

La forma de importar estas librerías es de la siguiente manera:

NumPy Array

El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a traves del indexado, a un dato específico o un grupo de muchos datos específicos.

In [5]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]


arr = np.array(lista)



In [6]:
type(arr)

numpy.ndarray

In [8]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Indexado:
Slicing de una matriz

In [9]:
matriz[1: , 0:2]

array([[4, 5],
       [7, 8]])

Esta forma de indexar o hacer slicing es propia del arrya de np

In [14]:
## Generar un array con numpy, por defecto es tipo int
arr = np.array([1,2,3,4])
arr.dtype
# dtype es una propiedad del objeto np.array

dtype('int64')

In [12]:
# Define el tipo de dato que quiere que sea cada elemento del array
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [15]:
# convertir a otro tipo, muy util para redes neuronales que suelen usar datos tipo float64
arr = arr.astype(np.float64)
# funcion astype cambia el tipo al formato indicado

In [16]:
# Tipo booleano
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [17]:
# Tipo string
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [18]:
# Tipo int
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)