<a href="https://colab.research.google.com/github/okuraseki/CursoEDA/blob/main/Dimensiones_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



Dimensiones

scalar: dim = 0 Un solo dato o valor

vector: dim = 1 Listas de Python

matriz: dim = 2 Hoja de cálculo

tensor: dim > 3 Series de tiempo o Imágenes



In [1]:
import numpy as np

In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim # nos muestra el numero de dimensiones

42


0

In [3]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [5]:
matriz = np.array([[1,2,3],[1,2,3]])
print(matriz)
matriz.ndim

[[1 2 3]
 [1 2 3]]


2

In [6]:
tensor = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


3

Agregar o eliminar dimensiones

In [8]:
vector = np.array([1,2,3], ndmin = 10) # esto le crea las dimensiones indicadas en el numero
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [11]:
# Expandiendo una dimension, axis 0 para eje x 1 para y, filas o columnas
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [12]:
# Eliminar una dimension
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) # elimina las dimensiones no usadas
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
