<a href="https://colab.research.google.com/github/okuraseki/CursoEDA/blob/main/condiciones_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Uso de condiciones

arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [5]:
# Genera un array con booleanos resultantes de la condicion > 5
arr_bool = arr > 5
arr_bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
# Tambien puedes elegir que valores cumplen la condicion y que genere un array con estos
arr[arr>5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [7]:
# o pasando el otro array como condicion
arr[arr_bool]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [8]:
arr[(arr > 5) & (arr < 9 )] # condiciones mas  complejas

array([6, 7, 8], dtype=int8)

In [10]:
arr[arr> 5] = 99 # cambia el valor de los datos que cumplan una condicion
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)