<a href="https://colab.research.google.com/github/okuraseki/CursoEDA/blob/main/funciones_principales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[ 4, 18, 17,  2, 11],
       [13, 14,  1, 13,  8]])

In [6]:
arr

array([ 4, 18, 17,  2, 11, 13, 14,  1, 13,  8])

In [7]:
arr.max()

18

In [8]:
matriz

array([[ 4, 18, 17,  2, 11],
       [13, 14,  1, 13,  8]])

In [17]:
matriz.max(0) # nos devuelve el valor maximo del indice (dimension dada), por cada posiscion,

array([13, 18, 17, 13, 11])

In [12]:
matriz.max(1) # aqui nos devuelve los 2 valores mas altos , 1 por cada elemento,

array([18, 14])

In [14]:
arr.argmax() # nos indica en que indice esta el valor mas alto

1

In [20]:
matriz.argmax() # cual d los 2 elementos es mayor

1

In [21]:
matriz.argmax(0) # por cada indice cual de los 2 es mayor

array([1, 0, 0, 1, 0])

In [22]:
matriz.argmax(1) # el indice de cada uno de los 2 elementos

array([1, 1])

In [23]:
arr.min() # equivalente para el minimo

1

In [24]:
arr.argmin() # esto igual

7

In [25]:
# La distancia de los valores, osea el valor max - min
arr.ptp()

17

In [31]:
# percentil, el valor del numero dado
np.percentile(arr,70) # en el nunmero indicamos el % que queremos

13.3

Calculo del percentil matematico:
 Teniendo n numeros ordenados de menor a mayor. Para calcualr el percentil 65, por ejemplo.
  20,30,45,53,67,89,123,145,158

  La formula:  k * n / 100     ->>> K (percentil) , n(numero de elementos)
  - 65 * 9 / 100 = 5,85
  Se toma como posicion el siguiente elemento del numero entero del resultado.
  En este caso 5,85 -> 6, el sexto elemento.
  - 89 seria el percentil 65

In [30]:
arr.sort() # ordena los elementos, aunque esto no es necesario para que la funcion percentile trabaje
arr

array([ 1,  2,  4,  8, 11, 13, 13, 14, 17, 18])

In [32]:
# para calcular la mediana, que el percentil 50
np.median(arr)

12.0

In [33]:
# Desviacion estandar:  Se utiliza para calcular la variación o dispersión en la que los puntos de datos individuales difieren de la media.
# es el promedio de las distancias de los datos individiales a la media.
np.std(arr)

5.769748694700662

In [34]:
# Varianza: es el promedio de las distancias al cuadrado que van desde las observaciones a la media
np.var(arr)

33.29

In [ ]:
# Es la media, que no es la mediana, la media es solo sumar los valores y dividir por el numero de estos
np.mean(arr)

In [35]:

a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [38]:
np.concatenate((a,b), axis=0) # une array siempre que las dimensiones sean igual, en este caso no lo son

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
# vamos a modificar las dimensiones del array b para poder concatenar
b = np.expand_dims(b, axis=0)
b.ndim

2

In [41]:
b

array([[5, 6]])

In [39]:
# ahora si lo concatena
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
# la T es la transpuesta de una matriz, si una matriz es 2,3 pasa a ser 3,2
# si queremos unir los 2 array, pero cambiando la forma en la que hizo antes, osea. En vez de 3 elementos con 2 cada, 2 elemntos con 3 cada
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [42]:
# Aqui nos da error, hay que usar la transpuesta de B, puesto que B tiene 1 elemento en la dimension 1(notese que aqui se refieren a index)
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])