<a href="https://colab.research.google.com/github/okuraseki/CursoEDA/blob/main/shape_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))

In [4]:
arr.shape # nos muesta el numero de filas y columnas

(3, 2)

In [5]:
arr

array([[3, 1],
       [3, 2],
       [8, 8]])

In [6]:
arr.reshape(1,6)
# cambia la forma del array, de 3 elementos de 2 a 1 elmento de 6

array([[3, 1, 3, 2, 8, 8]])

In [7]:
arr.reshape(2,3)

array([[3, 1, 3],
       [2, 8, 8]])

In [8]:
# tambien se puede hacer llamnando al metodo de clase
np.reshape(arr,(1,6)) # se le pasa como parametro el array y la forma

array([[3, 1, 3, 2, 8, 8]])

In [ ]:
# puedes indicarle que la reordeancion de los elementos los haga de la manera de ciertos lengunjes
# C , Fortran ,

In [9]:
arr

array([[3, 1],
       [3, 2],
       [8, 8]])

In [10]:
np.reshape(arr,(2,3),'C') # como en C

array([[3, 1, 3],
       [2, 8, 8]])

In [12]:
np.reshape(arr,(2,3), 'F') # como en fortran

array([[3, 8, 2],
       [3, 1, 8]])

In [13]:
np.reshape(arr,(2,3),'A') # como optimiza mi sistema

array([[3, 1, 3],
       [2, 8, 8]])

In [ ]:
# Siempre respetando los elementos que tenga el array inicial